Update Matomo Java Tracker to 3.2.0
digitalfabrik/entitlementcard pull request #1207
Opened 2023-11-14 17:31 UTC by dheid

### Hey @f1sh1918 and digitalfabrik team,

Just wanted to give your project a little boost with the latest and greatest from Matomo Java Tracker! 🚀

### Changes in a Nutshell:

- **Bug Fixes & Performance Boosts:** Say goodbye to some pesky bugs and enjoy a faster, smoother tracking experience.

- **Security Makeover:** We're getting the latest security swag to keep our project locked down.

- **Stay Cool with Compatibility:** Now we're best buddies with Matomo versions up to 5, so no more awkward compatibility issues.

- **Less Baggage:** Matomo Java Tracker 3.2.0 is lean and mean with fewer dependencies. Less stuff, more speed!

- **New Toys:** Check out the cool new dimension parameter for super-customizable tracking.

- **Java 11 Party:** We're upgrading to the latest Java 11 implementation. It's like giving our project a cool new set of wheels.

- **Smooth Moves:** If you're coming from version 2, no worries! There's a handy migration guide [here](https://github.com/matomo-org/matomo-java-tracker#migration-from-version-2-to-302) to make the switch painless.

### How to Test:

1. Update to Matomo Java Tracker version 3.2.0.
2. Make sure our project still builds like a champ.
3. Double-check that our Matomo tracking mojo is still on point.
4. Test out any new features and give that dimension parameter a spin.

### Where to Get Help:

- Dive into the [Javadoc](https://javadoc.io/doc/org.piwik.java.tracking/matomo-java-tracker/3.2.0/index.html) for the nitty-gritty details.
- Got issues or bright ideas? Hit up the [Matomo Java Tracker GitHub](https://github.com/matomo-org/matomo-java-tracker).

### Your Feedback Matters:

Give it a whirl and let us know how it goes! Your feedback is like gold to us. 🌟

Cheers,
Daniel

2023-11-15 12:05 UTC, f1sh1918 commented
thx @dheid for your contribution :)
We gonna check your pr and put it in our next major release

2023-11-15 21:19 UTC, dheid commented
@f1sh1918 That's great! Thank you very much!

2023-12-05 07:41 UTC, dheid commented
@f1sh1918 ping

2023-12-07 09:21 UTC, sarahsporck requested changes
Really awesome! Thanks for this PR! I left one small comment. Besides that this is ready to go.

---

Tested with AppSearch & CardActivation.

2023-12-07 09:21 UTC, sarahsporck commented on backend/src/main/kotlin/app/ehrenamtskarte/backend/matomo/Matomo.kt
>                  .searchQuery((params.searchText ?: "") + "?categories=" + (params.categoryIds?.joinToString(",") ?: ""))
Could you also split search query and search category, as this works now as intended? Would be awesome :)
```suggestion
     .searchCategory(params.categoryIds?.joinToString(","))
     .searchQuery(params.searchText ?: "")
```

2023-12-07 12:39 UTC, dheid commented
You're welcome! I accepted your changes and increased the version to 3.2.0.

2023-12-08 13:29 UTC, sarahsporck approved these changes
Very nice! Thanks a lot.

2023-12-08 13:30 UTC, merged