1400: Activate card confirmation mail per region
digitalfabrik/entitlementcard pull request #1401
Opened 2024-04-16 16:59 UTC by f1sh1918

### Short description

### Proposed changes

-
-

### Side effects

-
-

### Resolved issues

Fixes: #

2024-04-30 09:16 UTC, ztefanie requested changes
- Tested settings on Bayern, the settings are only visibale for the role region-admin. not for other roles or nuernberg. I expect this is the wanted behaviour.

- Route is protected, but when sending the request without authorization I get an 401 as expected. When I send a request with the authorization for the wrong region, i get an 200, with the message "Exception while fetching data (/result) : Insufficient access right" and a stack trace. I think this should als return a 401, without any additional data.

- Sending mails does not work for me. (It did previously and it also works on main). The PDF is created but an error is shown and no email is sent.) See the attached video:

https://github.com/digitalfabrik/entitlementcard/assets/18463686/af64c142-47ee-403b-9d88-e5ab10102087

2024-05-13 08:28 UTC, f1sh1918 commented on administration/src/bp-modules/cards/hooks/useCardGenerator.ts
> +      if (region.activatedForCardConfirmationMail) {
indeed. for nuernberg in general there is no "region verwalten" function. All region verwalten functions are connected to the applications which do not exist for nuernberg.
For bavaria region admins can adjust their settings individual

2024-05-13 08:29 UTC, f1sh1918 commented on backend/src/main/kotlin/app/ehrenamtskarte/backend/migration/migrations/V0011_AddRegionCardConfirmationMailActivation.kt
> +            ADD "activatedForCardConfirmationMail" BOOLEAN NOT NULL DEFAULT false;
yes as daniel told me, every region should opt-in this to activate

2024-05-13 10:07 UTC, f1sh1918 commented
> * Tested settings on Bayern, the settings are only visibale for the role region-admin. not for other roles or nuernberg. I expect this is the wanted behaviour.
> * Route is protected, but when sending the request without authorization I get an 401 as expected. When I send a request with the authorization for the wrong region, i get an 200, with the message "Exception while fetching data (/result) : Insufficient access right" and a stack trace. I think this should als return a 401, without any additional data.
> * Sending mails does not work for me. (It did previously and it also works on main). The PDF is created but an error is shown and no email is sent.) See the attached video:
> 
>  1400.mp4

1. is correct
2. i think a 403 should be correct and to throw a forbidden exception
3. i fixed that by surround it by a transaction

2024-05-21 07:51 UTC, ztefanie approved these changes
Not tested again. Looks good.

Using 403 Forbidden leads to exposing which resources exist even if not authorized, that why i suggested 401, but I am completely fine with using 401, just an explanation.

2024-05-21 07:52 UTC, merged