1609: Enable store import koblenz
digitalfabrik/entitlementcard pull request #1655
Opened 2024-10-01 12:30 UTC by f1sh1918

### Short description

As a store maintainer i want to upload the csv stores for koblenz

### Proposed changes

- move storeConfig to common and use it for koblenz and nuernberg
- add runConfig for project store manager creation for koblenz
- add nuernberg buildConfig as a placeholder for koblenz to get correct categories
- add TODO for getting correct buildConfig in administration
### Side effects

- none

### Testing

1. Create a store manager for koblenz
2. login as store manager
3. Go to Akzeptanzpartner verwalten
4. Upload stores
Find correct store file here: https://nextcloud.tuerantuer.org/index.php/apps/files/files/6468170
But you can also use same test files as for nuernberg

### Resolved issues

Fixes: #1609

2024-10-03 08:42 UTC, ztefanie requested changes
- Please add an example csv of the store upload to /administration/resources/stores

- Tested and is not working, when using the csv from nextcloud i get this error: Die erforderlichen Spalten sind nicht vorhanden oder nicht in der richtigen Reihenfolge.


Whenever you are sharing a nextcloud link it only opens the landing page for me. I do not have this problem when others are sharing links, i think the correct nextcloud link is:
https://nextcloud.tuerantuer.org/index.php/apps/files/files/6518906?dir=/Projects/Digitale%20Berechtigungskarte/Stadt%20Koblenz/Akzeptanzpartner&openfile=true
Not sure what you are sharing, but it seems not to work.

2024-10-03 10:41 UTC, f1sh1918 commented
to be honest i have no clue why its not working for you. I attached a working video @ztefanie 


https://github.com/user-attachments/assets/25b4110e-4296-4bea-a4d4-4f0e04df9b4b

I added a sample file to the repository since i don't want to upload the real csv from koblenz

2024-10-04 07:52 UTC, ztefanie commented
Tested again, works as expected :tada:

2024-10-07 11:13 UTC, steffenkleinle approved these changes
Tested on firefox, works as expected

2024-10-08 12:52 UTC, f1sh1918 commented on administration/src/project-configs/storeConfig.ts
>  export const storeConfig: StoresManagement = {
i use plural now

2024-10-08 12:53 UTC, f1sh1918 commented on administration/src/bp-modules/stores/__tests__/AcceptanceStoreEntry.test.ts
> +    `should be validated false store invalid entries for $projectConfig.name`,
i adjusted to sentence so sth clearer

2024-10-08 14:05 UTC, f1sh1918 commented
> Tested again, works as expected 🎉

can you please recheck and give me an approve if its fine @ztefanie

2024-10-09 06:54 UTC, ztefanie requested changes
The columns width is not really good. I do not like the hard coded widths, there are nice approaches to handle this dynamically, see here: https://github.com/palantir/blueprint/issues/1863#issuecomment-559633896

If entering chars (not numbers) or nothing for lat/long i get the wrong error message "Keine passenden Geodaten gefunden! Bitte prüfen sie die Adresse." If the lat/long is invalid, it should either show a message with the info lat/long is wrong or directly get it, if adress is valid.

Special chars should not be allowed in categoryId section, i can input there "10%" and get no error in the ui, but a 500 is thrown when clicking "import stores"

postalcode should only allow numbers

i did not check every field, but the field definitively need checks

2024-10-14 07:52 UTC, f1sh1918 commented
> Not really happy with only a frontend check, but as this is an endpoint only for logged in users, I think it is oke, but still bad practice.

there is an open issue for that

2024-10-14 08:15 UTC, merged